<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>A PHP Demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg mymenustyle">
            <div class="container-fluid">
            <a class="navbar-brand" href="index.html">Planet PHP</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav " >
                    <li class="nav-item" >
                        <a class="nav-link  mycolactive" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link mycol" href="#">&ltFirst PHP Script&gt</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link mycol" href="#">&ltProduct Lookup&gt</a>
                    </li>
                    <li class="nav-item mycol">
                        <a class="nav-link mycol" href="upload.html">&ltUpload Image&gt</a>
                    </li>
                    <li class="nav-item mycol">
                        <a class="nav-link mycol" href="#">&ltView Image Gallery&gt</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main>
        <h1>Here is some content generated by PHP</h1>
        <?php
            $number = rand(1,10);
            $margin = 50;
            for($i=0; $i<$number; $i++) {
			    echo('<h2 style = "margin-left: ' . $margin .  'px" >Hello World from Nick</h2>');
                echo("\r\n");
                $margin += 100;
		    }
            
        ?>
    </main>
   <footer>
        (C) ChatGPT Believe at your peril
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>
</html>